testing branch protectiong (again)
perezale/demo-gama pull request #2
Opened 2024-10-17 23:47 UTC by perezale

2024-10-17 23:52 UTC, ealcca requested changes
da error los test....

2024-10-17 23:56 UTC, ealcca requested changes
Impecable Ale! mandale noma!

2024-10-17 23:57 UTC, ealcca approved these changes
Perdon! Esta todo en orden, se puede subir...

2024-10-17 23:58 UTC, Dga1966 approved these changes
Ok

2024-10-18 00:03 UTC, ealcca approved these changes
Perfecto Ale!

2024-10-18 00:04 UTC, merged